#created for backward compatibility
from assembly2.importPart import ImportedPartViewProviderProxy
from assembly2.constraints.viewProviderProxy  import ConstraintViewProviderProxy, ConstraintMirrorViewProviderProxy
from assembly2.constraints.objectProxy import ConstraintObjectProxy, ConstraintMirrorObjectProxy
